added node methods for cid and tid requests returning promises and th…
mattgrill/drupal-org-api pull request #1
Opened 2017-07-19 16:12 UTC by ggcadc

added node methods for cid and tid requests returning promises and then mapping once resolved.

2017-08-09 18:23 UTC, mattgrill requested changes
Couple of other non-specific issues. 

`getRelatedTaxonomyTerms` should be called after fetching the node data, which contains the references to the related taxonomy terms.

`taxonomyTerm` returns a `Promise` so we can construct an array of requests, `Promise.all()` to fetch all the related terms and then handle the result.

2017-08-09 18:23 UTC, mattgrill commented on lib/index.js
> +      .catch(Promise.reject);
Lets not try and figure out how to handle errors in this PR.

2017-08-09 18:23 UTC, mattgrill commented on lib/index.js
> +  nodeTaxonomyId(filterOptions = {}) {
Lets normalize the method name, perhaps something like `getRelatedTaxonomyTerms`?

2017-08-09 18:23 UTC, mattgrill commented on lib/index.js
> +    return this.axios({ method, url })
We already have a request handler that should be used. Lets not add another reference to `axios` and all that comes with that.

2017-08-10 04:29 UTC, ggcadc commented
New commit covers all issues mentioned

2017-08-11 15:28 UTC, mattgrill requested changes
Looks like you accidentally included the `package-lock.json` from installing dependencies from with npm5.

2017-08-11 15:28 UTC, mattgrill commented on lib/index.js
> +    const taxonomyTermsArray = data.list[0].taxonomy_vocabulary_9;
I think we had talked about only accepting an array of `nid`'s? That way we don't have to even think about the format of the data, and then just check that the length of the array passed is greater than `0` and some basic sanity checks around the contents.

2017-08-15 23:21 UTC, mattgrill approved these changes

2017-08-15 23:22 UTC, merged